spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host:
    timeout:
    port:
datasource:
  gmssdk:
    jdbcUrl:
    username:
    password:
test:
  123
